export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_ITEM_QUANTITY = "INCREMENT_ITEM_QUANTITY";
export const DECREMENT_ITEM_QUANTITY = "DECREMENT_ITEM_QUANTITY";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAILED = "ORDERS_FAILED";

export const GET_BLOGS = "GET_BLOGS";
export const GET_BLOGS_LOADING = "GET_BLOGS_LOADING";
export const GET_BLOGS_LOADED = "GET_BLOGS_LOADED";
export const BLOGS_LAST_REACHED = "BLOGS_LAST_REACHED";

export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
